# Thanks for using YetAnotherBlockGame
# Ensure you look through all these options
# If you need help:
# Discord - https://discord.gg/BwWhCHUKDf
#
#----------------------------------------------------------#
#                      MAIN OPTIONS                        #
#----------------------------------------------------------#
#
# The prefix for all messages
chat-format: "&7[&6YABG&7] "
# The world used to generate the islands, if it doesn't exist we will create it
world-name: "yabg_world"
#
#----------------------------------------------------------#
#                      CHAT MESSAGE                        #
#----------------------------------------------------------#
#
messages:
  spawn-teleport: "&aYou have been teleported to spawn"
  spawn-not-set: "&cSpawn has not been set"
  player-only-command: "&cOnly players can use this command!"
  missing-permission: "&cYou do not have permission to use this command!"
#
#----------------------------------------------------------#
#                      ISLAND OPTIONS                      #
#----------------------------------------------------------#
#
island:
  # The island size
  size: 100
  # The island block
  block: "GRASS_BLOCK"
  # The island spawn location
  spawn-y: 100
#
#----------------------------------------------------------#
#                      PHASE OPTIONS                       #
#----------------------------------------------------------#
#
phases:
  begin:
    OAK_LOG:
      amount: 10
      possibility: 100
    OAK_LEAVES:
      amount: 10
      possibility: 100
    OAK_SAPLING:
      amount: 10
      possibility: 100
    DIRT:
      amount: 10
      possibility: 100
    GRASS_BLOCK:
      amount: 10
      possibility: 100
    COBBLESTONE:
      amount: 10
      possibility: 100
    TORCH:
      amount: 10
      possibility: 100
    CHEST:
      amount: 10
      possibility: 100
    OAK_PLANKS:
      amount: 10
      possibility: 100
  stage-1:
    SAND:
      amount: 10
      possibility: 100
    SANDSTONE:
      amount: 10
      possibility: 100
    CACTUS:
      amount: 10
      possibility: 100
    SUGAR_CANE:
      amount: 10
      possibility: 100
    ACACIA_LOG:
      amount: 10
      possibility: 100
    ACACIA_LEAVES:
      amount: 10
      possibility: 100
    ACACIA_SAPLING:
      amount: 10
      possibility: 100
    ACACIA_PLANKS:
      amount: 10
      possibility: 100