# Thanks for using YetAnotherBlockGame
# Ensure you look through all these options
# If you need help:
# Discord - https://discord.gg/BwWhCHUKDf
#
#----------------------------------------------------------#
#                      MAIN OPTIONS                        #
#----------------------------------------------------------#
#
# The prefix for all messages
chat-format: "&7[&6YABG&7] "
# The world used to generate the islands, if it doesn't exist we will create it
world-name: "yabg_world"
# Required to execute /setspawn
set-spawn-permission: "yabg.setspawn"
#
#----------------------------------------------------------#
#                      CHAT MESSAGE                        #
#----------------------------------------------------------#
#
messages:
  spawn-teleport: "&aYou have been teleported to spawn"
  spawn-not-set: "&cSpawn has not been set"
  player-only-command: "&cOnly players can use this command!"
  missing-permission: "&cYou do not have permission to use this command!"
  no-space-for-islands: "&cThere is no space for islands!"
  invalid-name: "&cInvalid name!"
  already-has-island: "&cYou already have an island!"
  island-created: "&aIsland created!"
  teleported-to-island: "&aYou have been teleported to your island!"
  dont-own-island: "&cYou do not own an island!"
  invalid-usage: "&cInvalid usage!"
  invalid-sub-command: "&cInvalid sub-command!"
  error-occurred: "&cAn error occurred: %s!"
  spawn-location-set: "&aSpawn location set!"
  not-allowed-to-leave: "&cYou are not allowed to leave your island!"
  welcome: "&aWelcome to YetAnotherBlockGame!"
#
#----------------------------------------------------------#
#                      ISLAND OPTIONS                      #
#----------------------------------------------------------#
#
island:
  # The island size
  size: 100
  # The island block
  block: "GRASS_BLOCK"
  # The island spawn location
  spawn-y: 100
#
#----------------------------------------------------------#
#                      PHASE OPTIONS                       #
#----------------------------------------------------------#
#
phases:
  # Every phase is defined by its name and a list of materials
  begin:
    OAK_LOG:
      # Amount defines how often this block has to be spawned to switch to the next phase
      amount: 10
      # Possibility defines the chance of this block to be spawned
      possibility: 100
    OAK_LEAVES:
      amount: 10
      possibility: 100
    DIRT:
      amount: 10
      possibility: 100
    GRASS_BLOCK:
      amount: 10
      possibility: 100
    COBBLESTONE:
      amount: 10
      possibility: 100
    OAK_PLANKS:
      amount: 10
      possibility: 100
  stage-1:
    SAND:
      amount: 10
      possibility: 100
    SANDSTONE:
      amount: 10
      possibility: 100
    CACTUS:
      amount: 10
      possibility: 100
    ACACIA_LOG:
      amount: 10
      possibility: 100
    ACACIA_LEAVES:
      amount: 10
      possibility: 100
    ACACIA_PLANKS:
      amount: 10
      possibility: 100