# Thanks for using YetAnotherBlockGame
# Ensure you look through all these options
# If you need help:
# Discord - https://discord.gg/BwWhCHUKDf
#
#----------------------------------------------------------#
#                      MAIN OPTIONS                        #
#----------------------------------------------------------#
#
# The prefix for all messages
chat-format: "&7[&6YABG&7] "
#
# The world used to generate the islands, if it doesn't exist we will create it
world:
  name: "yabg_world"
  island-size: 100
#
#----------------------------------------------------------#
#                      CHAT MESSAGE                        #
#----------------------------------------------------------#
#
messages:
  spawn-teleport: "&aYou have been teleported to spawn"
  spawn-not-set: "&cSpawn has not been set"
  player-only-command: "&cOnly players can use this command!"
  missing-permission: "&cYou do not have permission to use this command!"