name: YetAnotherBlockGame
main: de.florianmichael.yabg.BukkitPlugin
author: FlorianMichael/EnZaXD
version: ${version}
description: Advanced OneBlock SkyBlock implementation for Paper (and Spigot).
api-version: 1.13
folia-supported: true
commands:
  spawn:
    description: Teleport to the spawn location
    usage: /spawn
  setspawn:
    description: Set the spawn location
    usage: /setspawn
  island:
    description: Manage your island or visit another player's island
    usage: /island